-- Library: one place for every applicant's CV, details, notes, interview
-- summaries, transcripts and recordings. Staff with the "library" permission
-- open it, and can share a view-only copy of one applicant with someone who has
-- no account (a hiring manager, for example). The recipient proves they own the
-- email address with a one-time code; staff can turn a share off at any time.

alter table user_permissions drop constraint if exists user_permissions_permission_check;
alter table user_permissions add constraint user_permissions_permission_check
  check (permission in ('manage_accounts','job_management','job_posting','audit_trail','applicant_portal','library'));

-- Every current Admin starts with the Library; they can pass it on to HR.
insert into user_permissions (user_id, permission)
select id, 'library' from users where role = 'admin'
on conflict (user_id, permission) do nothing;

create table library_shares (
  id               bigint generated by default as identity primary key,
  application_id   bigint not null references applications(id) on delete cascade,
  token_hash       text not null unique,                 -- sha256 of the link token
  recipient_email  citext not null,
  recipient_name   text,
  message          text,
  sections         text[] not null,                      -- what the recipient sees
  allow_download   boolean not null default true,        -- the CV can be downloaded
  expires_at       timestamptz,                          -- null: until someone turns it off
  revoked_at       timestamptz,
  revoked_by       bigint references users(id) on delete set null,
  created_by       bigint references users(id) on delete set null,
  created_at       timestamptz not null default now(),
  last_opened_at   timestamptz,
  open_count       integer not null default 0
);
create index library_shares_application on library_shares (application_id, created_at desc);
alter table library_shares enable row level security;

-- One-time codes emailed to the recipient (stored hashed, short-lived, few tries).
create table library_share_codes (
  id          bigint generated by default as identity primary key,
  share_id    bigint not null references library_shares(id) on delete cascade,
  code_hash   text not null,
  attempts    integer not null default 0,
  expires_at  timestamptz not null,
  used_at     timestamptz,
  created_at  timestamptz not null default now()
);
create index library_share_codes_share on library_share_codes (share_id, created_at desc);
alter table library_share_codes enable row level security;

-- A verified viewer: the browser keeps the token for a few hours.
create table library_share_sessions (
  id          text primary key,                          -- sha256 of the viewer token
  share_id    bigint not null references library_shares(id) on delete cascade,
  expires_at  timestamptz not null,
  ip          text,
  created_at  timestamptz not null default now()
);
create index library_share_sessions_share on library_share_sessions (share_id);
alter table library_share_sessions enable row level security;

-- Meeting recordings: opt in per interview, recorded by the interviewer's
-- browser in five-minute pieces (camera tiles and everyone's sound).
alter table interviews add column record_meeting boolean not null default false;

create table interview_recordings (
  id            bigint generated by default as identity primary key,
  interview_id  bigint not null references interviews(id) on delete cascade,
  seq           integer not null check (seq >= 0),
  storage_path  text not null,
  mime_type     text not null,
  size_bytes    bigint not null default 0,
  duration_sec  integer not null default 0,
  started_at    timestamptz not null,
  created_at    timestamptz not null default now(),
  unique (interview_id, seq)
);
create index interview_recordings_interview on interview_recordings (interview_id, seq);
alter table interview_recordings enable row level security;

do $$
begin
  if exists (select 1 from information_schema.schemata where schema_name = 'storage') then
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values
      ('recordings', 'recordings', false, 26214400, array['video/webm','video/mp4','audio/webm'])
    on conflict (id) do nothing;
  end if;
end $$;
