-- Final interviews: external stakeholders (department heads, clients) join the
-- built-in room through a shareable guest link and wait until a host admits them.

-- The guest link carries its own token, separate from the candidate's, so a
-- forwarded guest link never grants the candidate's access (or the reverse).
alter table interviews
  add column is_final    boolean not null default false,
  add column guest_token text unique;

create table interview_guests (
  id            bigint generated by default as identity primary key,
  interview_id  bigint not null references interviews(id) on delete cascade,
  -- Secret held by the guest's browser; proves which request is theirs.
  guest_key     text not null unique,
  name          text not null check (char_length(name) between 1 and 120),
  position      text not null check (char_length(position) between 1 and 120),
  state         text not null default 'waiting' check (state in ('waiting','admitted','denied','left')),
  requested_at  timestamptz not null default now(),
  decided_at    timestamptz,
  decided_by    bigint references users(id) on delete set null,
  last_seen     timestamptz not null default now(),
  created_at    timestamptz not null default now()
);
create index interview_guests_interview on interview_guests (interview_id, state, requested_at);

alter table interview_guests enable row level security;
