-- Acme People ATS — PostgreSQL baseline.
-- Consolidates MySQL schema.sql plus migrations 001–018 of the PHP system.
-- Identity columns are GENERATED BY DEFAULT so the MySQL import can keep every
-- existing id (scripts/import-mysql.ts resets the sequences afterwards).
-- Payroll and leave tables stay retired (migration 017); interview_ice_candidates
-- is not carried over because signalling no longer touches the database.

create extension if not exists citext;

-- ---------------------------------------------------------------------------
-- Accounts and access
-- ---------------------------------------------------------------------------
create table users (
  id                  bigint generated by default as identity primary key,
  name                text not null check (char_length(name) between 1 and 120),
  email               citext not null unique,
  password_hash       text not null,
  profile_image       text,
  job_title           text,
  role                text not null default 'recruiter'
                      check (role in ('super_admin','admin','recruiter','hiring_manager','employee')),
  active              boolean not null default true,
  account_status      text not null default 'active'
                      check (account_status in ('pending','active','rejected','suspended','disabled','pending_reactivation')),
  created_by          bigint references users(id) on delete set null,
  hr_account_limit    integer not null default 0 check (hr_account_limit between 0 and 999),
  seat_released       boolean not null default false,
  approved_by         bigint references users(id) on delete set null,
  approved_at         timestamptz,
  status_note         text,
  password_changed_at timestamptz,
  created_at          timestamptz not null default now(),
  constraint users_active_mirrors_status check (active = (account_status = 'active'))
);
create index users_role_status on users (role, account_status);
create index users_created_by on users (created_by);

create table user_permissions (
  id          bigint generated by default as identity primary key,
  user_id     bigint not null references users(id) on delete cascade,
  permission  text not null check (permission in ('manage_accounts','job_management','job_posting','audit_trail','applicant_portal')),
  granted_by  bigint references users(id) on delete set null,
  created_at  timestamptz not null default now(),
  unique (user_id, permission)
);

create table sessions (
  id            text primary key,                 -- sha256 of the cookie token
  user_id       bigint not null references users(id) on delete cascade,
  csrf_token    text not null,
  remember      boolean not null default false,
  ip_address    text,
  user_agent    text,
  created_at    timestamptz not null default now(),
  last_seen_at  timestamptz not null default now(),
  expires_at    timestamptz not null
);
create index sessions_user on sessions (user_id);
create index sessions_expiry on sessions (expires_at);

create table account_requests (
  id            bigint generated by default as identity primary key,
  user_id       bigint not null references users(id) on delete cascade,
  requested_by  bigint references users(id) on delete set null,
  request_type  text not null default 'reactivation' check (request_type in ('reactivation')),
  reason        text,
  status        text not null default 'pending' check (status in ('pending','approved','rejected')),
  decided_by    bigint references users(id) on delete set null,
  decided_at    timestamptz,
  decision_note text,
  created_at    timestamptz not null default now()
);
create index account_requests_open on account_requests (status, created_at);
create unique index account_requests_one_pending on account_requests (user_id) where status = 'pending';

create table password_reset_requests (
  id                bigint generated by default as identity primary key,
  user_id           bigint not null references users(id) on delete cascade,
  reason            text,
  status            text not null default 'pending' check (status in ('pending','approved','rejected','used','expired')),
  reset_token_hash  text unique,
  token_expires_at  timestamptz,
  decided_by        bigint references users(id) on delete set null,
  decided_at        timestamptz,
  decision_note     text,
  requested_ip      text,
  created_at        timestamptz not null default now()
);
create index reset_open on password_reset_requests (status, created_at);
create unique index reset_one_pending on password_reset_requests (user_id) where status = 'pending';

-- ---------------------------------------------------------------------------
-- Settings, departments, jobs
-- ---------------------------------------------------------------------------
create table settings (
  setting_key   text primary key,
  setting_value text not null
);

create table departments (
  id          bigint generated by default as identity primary key,
  name        text not null unique,
  description text,
  created_at  timestamptz not null default now()
);

create table jobs (
  id                   bigint generated by default as identity primary key,
  department_id        bigint references departments(id) on delete set null,
  title                text not null,
  slug                 text not null unique,
  location             text,
  employment_type      text not null default 'full_time'
                       check (employment_type in ('full_time','part_time','contract','internship')),
  tags                 text,
  applicant_limit      integer check (applicant_limit is null or applicant_limit >= 0),
  description          text,
  requirements         text,
  responsibilities     text,
  qualifications       text,
  preferred_skills     text,
  experience_required  text,
  education_required   text,
  salary_info          text,
  is_urgent            boolean not null default false,
  source_pdf           text,
  status               text not null default 'draft' check (status in ('draft','open','paused','closed')),
  approval_status      text not null default 'none'
                       check (approval_status in ('none','draft','pending','approved','rejected','changes_requested')),
  owner_id             bigint references users(id) on delete set null,
  created_by           bigint references users(id) on delete set null,
  submitted_by         bigint references users(id) on delete set null,
  submitted_at         timestamptz,
  reviewed_by          bigint references users(id) on delete set null,
  reviewed_at          timestamptz,
  review_note          text,
  published_at         timestamptz,
  created_at           timestamptz not null default now()
);
create index jobs_approval on jobs (approval_status, status);
create index jobs_public on jobs (status, published_at desc);
create index jobs_created_by on jobs (created_by);

create table job_approvals (
  id          bigint generated by default as identity primary key,
  job_id      bigint not null references jobs(id) on delete cascade,
  actor_id    bigint references users(id) on delete set null,
  action      text not null check (action in ('submitted','approved','rejected','changes_requested','published','resubmitted','withdrawn')),
  note        text,
  created_at  timestamptz not null default now()
);
create index job_approval_job on job_approvals (job_id, created_at);

-- ---------------------------------------------------------------------------
-- Candidates and applications
-- ---------------------------------------------------------------------------
create table candidates (
  id                bigint generated by default as identity primary key,
  first_name        text not null,
  last_name         text not null default '',
  email             citext not null,
  phone             text,
  current_title     text,
  experience_level  text check (experience_level in ('entry','mid','senior','lead')),
  skills            text,
  education         text,
  notes             text,
  resume_path       text,
  resume_text       text,
  profile_image     text,
  portfolio_url     text,
  source            text not null default 'career_site',
  rating            smallint not null default 0 check (rating between 0 and 5),
  record_status     text not null default 'active' check (record_status in ('draft','active')),
  consent_at        timestamptz,
  created_by        bigint references users(id) on delete set null,
  created_at        timestamptz not null default now(),
  search_vector     tsvector generated always as (
    to_tsvector('simple',
      coalesce(first_name,'') || ' ' || coalesce(last_name,'') || ' ' || coalesce(email::text,'') || ' ' ||
      coalesce(current_title,'') || ' ' || coalesce(skills,'') || ' ' || coalesce(resume_text,''))
  ) stored
);
-- Not unique: manual drafts may have no email yet, and legacy MySQL data never enforced it.
create index candidates_email on candidates (email);
create index candidates_record_status on candidates (record_status, created_at);
create index candidates_search on candidates using gin (search_vector);

create table applications (
  id            bigint generated by default as identity primary key,
  candidate_id  bigint not null references candidates(id) on delete cascade,
  job_id        bigint not null references jobs(id) on delete cascade,
  stage         text not null default 'new' check (stage in ('new','screening','interview','offer','hired','rejected')),
  status        text not null default 'active' check (status in ('active','withdrawn')),
  cover_letter  text,
  why_us        text,
  assigned_to   bigint references users(id) on delete set null,
  applied_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (candidate_id, job_id)
);
create index application_job on applications (job_id);
create index application_assigned on applications (assigned_to, stage);
create index application_stage on applications (status, stage, updated_at desc);

create table candidate_documents (
  id             bigint generated by default as identity primary key,
  candidate_id   bigint references candidates(id) on delete cascade,
  storage_path   text not null unique,
  original_name  text not null,
  extension      text not null check (extension in ('pdf','doc','docx')),
  mime_type      text,
  byte_size      integer not null default 0,
  is_primary     boolean not null default true,
  parsed         boolean not null default false,
  uploaded_by    bigint references users(id) on delete set null,
  created_at     timestamptz not null default now()
);
create index doc_candidate on candidate_documents (candidate_id, is_primary, created_at desc);

create table candidate_notes (
  id            bigint generated by default as identity primary key,
  candidate_id  bigint not null references candidates(id) on delete cascade,
  author_id     bigint references users(id) on delete set null,
  note          text not null,
  created_at    timestamptz not null default now()
);
create index candidate_notes_candidate on candidate_notes (candidate_id, created_at desc);

create table candidate_feedback (
  id              bigint generated by default as identity primary key,
  application_id  bigint not null references applications(id) on delete cascade,
  author_id       bigint references users(id) on delete set null,
  fit             text not null check (fit in ('strong-fit','potential-fit','not-a-fit')),
  notes           text,
  created_at      timestamptz not null default now()
);
create index candidate_feedback_app on candidate_feedback (application_id, created_at desc);

create table candidate_role_suggestions (
  id                bigint generated by default as identity primary key,
  application_id    bigint not null references applications(id) on delete cascade,
  suggested_job_id  bigint not null references jobs(id) on delete cascade,
  note              text,
  author_id         bigint references users(id) on delete set null,
  created_at        timestamptz not null default now()
);
create index role_suggestions_app on candidate_role_suggestions (application_id, created_at desc);

create table stage_reviews (
  id              bigint generated by default as identity primary key,
  application_id  bigint not null references applications(id) on delete cascade,
  stage_type      text not null check (stage_type in ('screening','interview')),
  rating          smallint check (rating between 0 and 100),
  feedback        text,
  notes           text,
  reviewer_id     bigint references users(id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (application_id, stage_type)
);

create table candidate_ai_analysis (
  id               bigint generated by default as identity primary key,
  application_id   bigint not null unique references applications(id) on delete cascade,
  overall_score    smallint not null check (overall_score between 0 and 100),
  category_scores  jsonb not null,
  summary          text not null,
  strengths        jsonb not null,
  concerns         jsonb not null,
  recommendation   text not null,
  ai_notes         text not null,
  generated_at     timestamptz not null default now()
);

create table offers (
  id              bigint generated by default as identity primary key,
  application_id  bigint not null references applications(id) on delete cascade,
  salary          numeric(12,2),
  start_date      date,
  status          text not null default 'draft' check (status in ('draft','sent','accepted','declined','expired')),
  notes           text,
  created_at      timestamptz not null default now()
);

create table referrals (
  id               bigint generated by default as identity primary key,
  referrer_name    text not null,
  referrer_email   citext not null,
  candidate_name   text not null,
  candidate_email  citext not null,
  job_id           bigint references jobs(id) on delete set null,
  notes            text,
  status           text not null default 'new' check (status in ('new','contacted','hired','closed')),
  created_at       timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Interviews
-- ---------------------------------------------------------------------------
create table interviews (
  id                        bigint generated by default as identity primary key,
  application_id            bigint not null references applications(id) on delete cascade,
  interviewer_id            bigint references users(id) on delete set null,
  meeting_type              text not null default 'interview' check (meeting_type in ('screening','interview')),
  starts_at                 timestamptz not null,
  ends_at                   timestamptz,
  timezone                  text,
  interview_type            text not null default 'video' check (interview_type in ('phone','video','onsite','panel')),
  meeting_url               text,
  meeting_provider          text not null default 'Acme Room',
  room_code                 text unique,
  candidate_token           text unique,
  location                  text,
  status                    text not null default 'scheduled'
                            check (status in ('scheduled','confirmed','completed','cancelled','no_show')),
  meeting_state             text not null default 'scheduled'
                            check (meeting_state in ('scheduled','ready','in_progress','ended','review_pending','reviewed')),
  notes                     text,
  live_notes                text,
  notes_updated_at          timestamptz,
  notes_author_id           bigint references users(id) on delete set null,
  feedback                  text,
  score                     smallint check (score between 0 and 100),
  recommendation            text check (recommendation in ('proceed','offer','hold','more_info','reject')),
  started_at                timestamptz,
  ended_at                  timestamptz,
  reviewed_at               timestamptz,
  reviewer_id               bigint references users(id) on delete set null,
  candidate_joined_at       timestamptz,
  candidate_request_state   text not null default 'none'
                            check (candidate_request_state in ('none','waiting','requested','admitted')),
  candidate_requested_at    timestamptz,
  candidate_admitted_at     timestamptz,
  candidate_admitted_by     bigint references users(id) on delete set null,
  candidate_last_seen       timestamptz,
  interviewer_last_seen     timestamptz,
  assistant_enabled         boolean not null default false,
  reminder_sent_at          timestamptz,
  created_by                bigint references users(id) on delete set null,
  created_at                timestamptz not null default now()
);
create index interview_start on interviews (starts_at);
create index interview_application on interviews (application_id);
create index interview_interviewer on interviews (interviewer_id, starts_at);
create index interview_meeting_state on interviews (meeting_state, starts_at);
create index interview_waiting on interviews (candidate_request_state, candidate_requested_at);
create unique index interview_no_double_booking on interviews (interviewer_id, starts_at)
  where status not in ('cancelled');

create table interview_signals (
  interview_id  bigint primary key references interviews(id) on delete cascade,
  connected_at  timestamptz,
  ended_at      timestamptz,
  created_at    timestamptz not null default now()
);

create table scorecard_ratings (
  id            bigint generated by default as identity primary key,
  interview_id  bigint not null references interviews(id) on delete cascade,
  reviewer_id   bigint not null references users(id) on delete cascade,
  criterion     text not null,
  rating        smallint not null check (rating between 1 and 5),
  updated_at    timestamptz not null default now(),
  unique (interview_id, reviewer_id, criterion)
);

create table interview_moments (
  id            bigint generated by default as identity primary key,
  interview_id  bigint not null references interviews(id) on delete cascade,
  user_id       bigint references users(id) on delete set null,
  at_second     integer not null check (at_second >= 0),
  label         text not null,
  created_at    timestamptz not null default now()
);
create index interview_moments_interview on interview_moments (interview_id, at_second);

create table assistant_notes (
  id            bigint generated by default as identity primary key,
  interview_id  bigint not null references interviews(id) on delete cascade,
  at_second     integer not null check (at_second >= 0),
  topic         text,
  text          text not null,
  created_at    timestamptz not null default now()
);
create index assistant_notes_interview on assistant_notes (interview_id, at_second);

-- ---------------------------------------------------------------------------
-- People and attendance
-- ---------------------------------------------------------------------------
create table employees (
  id                bigint generated by default as identity primary key,
  user_id           bigint unique references users(id) on delete set null,
  candidate_id      bigint references candidates(id) on delete set null,
  application_id    bigint unique references applications(id) on delete set null,
  applied_position  text,
  employee_number   text unique,
  job_title         text,
  department_id     bigint references departments(id) on delete set null,
  start_date        date,
  status            text not null default 'active' check (status in ('active','on_leave','terminated')),
  created_at        timestamptz not null default now()
);

create table work_schedules (
  id             bigint generated by default as identity primary key,
  name           text not null unique,
  timezone       text not null default 'Asia/Manila',
  start_time     time not null default '09:00',
  end_time       time not null default '18:00',
  break_minutes  smallint not null default 60,
  grace_minutes  smallint not null default 10,
  work_days      text[] not null default array['mon','tue','wed','thu','fri'],
  active         boolean not null default true,
  created_at     timestamptz not null default now()
);

create table employee_schedules (
  employee_id     bigint primary key references employees(id) on delete cascade,
  schedule_id     bigint not null references work_schedules(id) on delete restrict,
  effective_from  date not null,
  effective_to    date
);

create table holidays (
  id            bigint generated by default as identity primary key,
  name          text not null,
  holiday_date  date not null unique,
  is_paid       boolean not null default true
);

create table attendance_records (
  id              bigint generated by default as identity primary key,
  employee_id     bigint not null references employees(id) on delete cascade,
  work_date       date not null,
  clock_in        timestamptz,
  clock_out       timestamptz,
  break_minutes   smallint not null default 0,
  worked_minutes  integer,
  status          text not null default 'present'
                  check (status in ('present','late','absent','half_day','on_leave','holiday','incomplete')),
  source          text not null default 'self_service' check (source in ('self_service','admin','import')),
  notes           text,
  approved_by     bigint references users(id) on delete set null,
  approved_at     timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (employee_id, work_date)
);
create index attendance_date on attendance_records (work_date);

create table attendance_breaks (
  id             bigint generated by default as identity primary key,
  attendance_id  bigint not null references attendance_records(id) on delete cascade,
  break_start    timestamptz not null,
  break_end      timestamptz
);

create table attendance_corrections (
  id                   bigint generated by default as identity primary key,
  attendance_id        bigint not null references attendance_records(id) on delete cascade,
  requested_by         bigint not null references users(id) on delete cascade,
  requested_clock_in   timestamptz,
  requested_clock_out  timestamptz,
  reason               text not null,
  status               text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by          bigint references users(id) on delete set null,
  reviewed_at          timestamptz,
  created_at           timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Notifications and audit
-- ---------------------------------------------------------------------------
create table notifications (
  id            bigint generated by default as identity primary key,
  user_id       bigint not null references users(id) on delete cascade,
  actor_id      bigint references users(id) on delete set null,
  type          text not null default 'general',
  category      text not null default 'system' check (category in ('application','interview','message','system')),
  priority      text not null default 'medium' check (priority in ('low','medium','high','urgent')),
  title         text not null check (char_length(title) <= 200),
  body          text check (char_length(body) <= 500),
  link          text,
  action_label  text,
  entity_type   text,
  entity_id     bigint,
  read_at       timestamptz,
  created_at    timestamptz not null default now()
);
create index notification_inbox on notifications (user_id, read_at, created_at desc);

create table audit_logs (
  id           bigint generated by default as identity primary key,
  user_id      bigint references users(id) on delete set null,
  action       text not null,
  entity_type  text,
  entity_id    bigint,
  details      jsonb,
  ip_address   text,
  created_at   timestamptz not null default now()
);
create index audit_created on audit_logs (created_at desc);
create index audit_user on audit_logs (user_id, created_at desc);
create index audit_entity on audit_logs (entity_type, entity_id);
create index audit_action on audit_logs (action);

-- ---------------------------------------------------------------------------
-- Platform plumbing (new with the Node stack)
-- ---------------------------------------------------------------------------
create table pending_uploads (
  id             uuid primary key,
  purpose        text not null check (purpose in ('resume','candidate_photo','user_photo','job_pdf')),
  storage_path   text not null unique,
  original_name  text not null,
  declared_size  integer not null,
  declared_mime  text,
  created_by     bigint references users(id) on delete cascade,
  consumed_at    timestamptz,
  expires_at     timestamptz not null,
  created_at     timestamptz not null default now()
);
create index pending_uploads_expiry on pending_uploads (expires_at) where consumed_at is null;

create table email_outbox (
  id               bigint generated by default as identity primary key,
  idempotency_key  text not null unique,
  template         text not null,
  to_address       text not null,
  subject          text not null,
  status           text not null check (status in ('sending','sent','failed','skipped')),
  provider         text,
  provider_id      text,
  error            text,
  attempts         integer not null default 1,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create table integration_events (
  id           bigint generated by default as identity primary key,
  target       text not null default 'n8n',
  event        text not null,
  payload      jsonb not null,
  status       text not null check (status in ('delivered','failed','skipped')),
  http_status  integer,
  error        text,
  created_at   timestamptz not null default now()
);
create index integration_events_created on integration_events (created_at desc);

create table rate_limits (
  bucket        text primary key,
  window_start  timestamptz not null,
  hits          integer not null
);

-- ---------------------------------------------------------------------------
-- Row level security: the browser never talks to these tables directly.
-- Only the Node API (service connection) reads and writes them, so RLS is on
-- with no policies, which denies the anon and authenticated roles outright.
-- ---------------------------------------------------------------------------
do $$
declare t record;
begin
  for t in select tablename from pg_tables where schemaname = 'public' loop
    execute format('alter table public.%I enable row level security', t.tablename);
  end loop;
end $$;
