-- AI notes in the interview room: what was said (transcribed in short pieces by
-- the "Interview notes" n8n flow) and the summary written when the meeting ends.
-- Only the interviewer sees the live notes; the summary is part of the review.
create table interview_transcripts (
  id            bigint generated by default as identity primary key,
  interview_id  bigint not null references interviews(id) on delete cascade,
  at_second     integer not null check (at_second >= 0),
  text          text not null,
  created_at    timestamptz not null default now()
);
create index interview_transcripts_interview on interview_transcripts (interview_id, at_second);
alter table interview_transcripts enable row level security;

alter table interviews add column ai_summary jsonb;
alter table interviews add column ai_summary_at timestamptz;
