/** Countries offered by the phone selector on the application form: [ISO code, name, dialing code]. */
export const PHONE_COUNTRIES: ReadonlyArray<readonly [string, string, string]> = [
  ['PH', 'Philippines', '63'],
  ['US', 'United States', '1'],
  ['CA', 'Canada', '1'],
  ['GB', 'United Kingdom', '44'],
  ['JP', 'Japan', '81'],
  ['KR', 'South Korea', '82'],
  ['SG', 'Singapore', '65'],
  ['AU', 'Australia', '61'],
  ['DE', 'Germany', '49'],
  ['FR', 'France', '33'],
  ['IN', 'India', '91'],
  ['CN', 'China', '86'],
  ['ID', 'Indonesia', '62'],
  ['MY', 'Malaysia', '60'],
  ['TH', 'Thailand', '66'],
  ['VN', 'Vietnam', '84'],
  ['NZ', 'New Zealand', '64'],
  ['IE', 'Ireland', '353'],
  ['NL', 'Netherlands', '31'],
  ['ES', 'Spain', '34'],
  ['IT', 'Italy', '39'],
  ['PT', 'Portugal', '351'],
  ['CH', 'Switzerland', '41'],
  ['SE', 'Sweden', '46'],
  ['NO', 'Norway', '47'],
  ['DK', 'Denmark', '45'],
  ['FI', 'Finland', '358'],
  ['PL', 'Poland', '48'],
  ['AT', 'Austria', '43'],
  ['BE', 'Belgium', '32'],
  ['BR', 'Brazil', '55'],
  ['MX', 'Mexico', '52'],
  ['AR', 'Argentina', '54'],
  ['CL', 'Chile', '56'],
  ['CO', 'Colombia', '57'],
  ['ZA', 'South Africa', '27'],
  ['NG', 'Nigeria', '234'],
  ['KE', 'Kenya', '254'],
  ['EG', 'Egypt', '20'],
  ['AE', 'United Arab Emirates', '971'],
  ['SA', 'Saudi Arabia', '966'],
  ['IL', 'Israel', '972'],
  ['TR', 'Turkey', '90'],
  ['RU', 'Russia', '7'],
  ['UA', 'Ukraine', '380'],
  ['GR', 'Greece', '30'],
  ['CZ', 'Czech Republic', '420'],
  ['HU', 'Hungary', '36'],
  ['RO', 'Romania', '40'],
  ['HK', 'Hong Kong', '852'],
  ['TW', 'Taiwan', '886'],
  ['PK', 'Pakistan', '92'],
  ['BD', 'Bangladesh', '880'],
  ['LK', 'Sri Lanka', '94'],
  ['NP', 'Nepal', '977'],
  ['QA', 'Qatar', '974'],
  ['KW', 'Kuwait', '965'],
  ['OM', 'Oman', '968'],
  ['BH', 'Bahrain', '973'],
  ['JO', 'Jordan', '962'],
  ['LB', 'Lebanon', '961'],
  ['MA', 'Morocco', '212'],
  ['GH', 'Ghana', '233'],
];

export function dialCodeFor(iso: string): string {
  return PHONE_COUNTRIES.find(([code]) => code === iso)?.[2] ?? '63';
}

/** Flag emoji from the ISO code's regional indicator symbols. */
export function countryFlag(iso: string): string {
  return [...iso.toUpperCase()].map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65)).join('');
}
